### ISSUE TITLE
Opt-in data Tracking Feature

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/px-wp-insights#3]
Related to https://github.com/ampproject/amp-wp/issues/4651

Using https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines

Upon receiving user's consent, below are some data sets that we can capture for different purposes

- [x] WP Core/Other Data
- [x] AMP-WP Plugin Settings Data 
- [x] Error Data

Aside from capturing data, this feature should include:

- [ ] A way for users to see what data is sent
- [ ] A dedicated page in http://amp-wp.org/documentation/ explaining what we collect and how we use data.

**Comment by dhaval-parekh** [comment]
This feature is implemented in AMP plugin version 2.2. Which provide UI as well as CLI command to send support data.
